//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oprema()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
        }
    
        public int ID_oprema { get; set; }
        public string dobavljac { get; set; }
        public System.DateTime datum { get; set; }
        public string izvorFinancija { get; set; }
        public string nazivProjekta { get; set; }
        public string vrstaOpreme { get; set; }
        public string nazivOpreme { get; set; }
        public string opisOpreme { get; set; }
        public string zaprimac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
    }
}
